#!/bin/sh
# usage: do_bench program subdir ctltag
# i.e. do_bench relerr.paragon paragon test100knln
echo $1 $2 $3
mkdir $2
#echo 128
#$1 -sz 128 $3.ctl > $2/out.$3.d7
#echo 64
#$1 -sz 64 $3.ctl > $2/out.$3.d6
echo 32
$1 -sz 32 $3.ctl > $2/out.$3.d5
echo 16
$1 -sz 16 $3.ctl > $2/out.$3.d4
echo 8
$1 -sz 8 $3.ctl > $2/out.$3.d3
echo 4
$1 -sz 4 $3.ctl > $2/out.$3.d2
echo 2
$1 -sz 2 $3.ctl > $2/out.$3.d1
echo 1
$1 -sz 1 $3.ctl > $2/out.$3.d0















